# Generated by Django 5.2.1 on 2025-05-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("debates", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
    ]
