# Generated by Django 5.2.1 on 2025-09-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("debates", "0003_alter_ticket_options_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes"),
        ),
    ]
